CREATE TABLE IF NOT EXISTS public.abandoned_mines
(
    site_code character varying,
    wabmines_n character varying,
    feature_gr text,
    feature_ty text,
    site_type text,
    site_sub_t text,
    latitude numeric,
    longitude numeric,
    mga_zone integer,
    easting numeric,
    northing numeric,
    commoditie text,
    commodity_,
    target_com text,
    observatio date,
    originator text,
    bund text,
    bund_max numeric,
    bund_min numeric,
    condition text,
    visibility text,
    visual_imp,
    length numeric,
    width numeric,
    depth text,
    height numeric,
    strike numeric,
    azimuth numeric,
    dip numeric,
    edge_stabi text,
    base_condi text,
    excavation text,
    fences text,
    signs text,
    mf_shape text,
    revegetati text",
    ug_timbers text,
    ug_access text,
    headframe text,
    ug_seal_ty text,
    ug_seal_co text,
    open_cut_o text,
    water_cond text,
    ramp text,
    dump_mater text,
    dump_other text,
    dispersion text,
    dispersi00 numeric,
    site_confi text,
    point_conf text,
    web_link text,
    CONSTRAINT abandoned_mines_pkey PRIMARY KEY (site_code)
)

